### ISSUE TITLE
ALINHAMENTO DE TEXTO E CORREÇÃO DE BUG

### ISSUE THREAD

**Issue by ghost** [italozaina/projection-html5-icm#6]
Olá! eu achei mto bom.... principalmente o layout da coletanea, bem bonito e simplificado... só queria dar uma sugestão: os louvores estão centralizados... eu acharia melhor alinhados à esquerda como é padrão na MDT, ou ter uma opção pra mudar isso. queria tbm sugerir a correção de um bug... quando eu clico em um louvor na lista pra projeção, não acontece nada... eu tenho que descer toda a parte ali no "ao vivo" pra achar o louvor... se corrigir esses detalhes eu usarei concerteza!

**Comment by italozaina** [comment]
Primeiramente algumas considerações:

- Um dos motivos de eu criar esta forma de projeção é o formato ajustável tanto para datashow quanto monitores (16x9 ou 4:3) que ficava horrível na antiga coletânea MDT. Sempre sobrava margens laterais, ou esticava o fundo ou decentralizava as letras.
- Como solução estética testei a opção de alinhado a esquerda porém o resultado é muito ruim em uma apresentação, então optei por não disponibilizar esta opção, no caso a melhor opção para um sistema responsivo foi centralizar os textos para a projeção.

Na versão beta v0.9.5 (https://github.com/italozaina/projection-html5-icm/releases/tag/v0.9.5-beta) foi acrescentado a opção de clicar sobre os itens na "Lista para projeção" e iniciar a projeção do mesmo e também rolando a aba "Ao vivo" até o item.
![enviar_comment](https://user-images.githubusercontent.com/10713452/39958912-21ab32ea-55e0-11e8-9a8c-728ac2be9d09.png)


https://github.com/italozaina/projection-html5-icm/releases/tag/v0.9.5-beta
