### ISSUE TITLE
Louvores da coletanea antiga

### ISSUE THREAD

**Issue by ghost** [italozaina/projection-html5-icm#7]
Olá!
Queria ver a possibilidade de além da coletanea 2018, adicionar uma pasta com a coletanea antiga, pq alguns louvores ainda cantamos por aqui, como "eram cem ovelhas" por exemplo!! não sei em outras igrejas, mas creio que sim! ou criar um arquivo de dados e deixar disponível para escolha!
Obrigado!

**Comment by italozaina** [comment]
Olá a opção de adicionar novas pastas e louvores já existe. No canto superior esquerdo tem um botão para criar nova pasta e criar novas músicas.

**Comment by ghost** [comment]
Mas no caso, eu teria que digitar ou colar todos os louvores novamente fazendo isso??

**Comment by italozaina** [comment]
O sistema armazena uma vez que foi aberto no próprio navegador. Assim que criar uma vez a pasta com os louvores você sempre terá acesso ao abrir novamente. E também poderá exportar sua lista caso deseje passar pra outra pessoa ou apenas incluir em outro PC.

**Comment by ghost** [comment]
Não meu irmão isso eu sei... na verdade é que eu queria um arquivo de dados com a coletanea antiga, porque caso eu for fazer isso manualmente vai dar um trabalhão rsrs mas se vocês só tem a nova disponivel, eu me conformo!

**Comment by italozaina** [comment]
Ahh sim entendi. Bom seria mais ou menos o mesmo trabalho que eu tive para produção da 2018 e da CIA 2017. Que ainda estão carente de correção. 

Se o irmão tiver interesse e habilidades com programação posso explicar como criar uma pasta de forma mais prática, porém via código JSON. Assim teríamos mais essa opção dos louvores antigos.

Eu ficaria muito feliz se pudesse dividir o fardo de gerar conteúdo para o sistema. Bom fica aí o convite :D

**Comment by ghost** [comment]
Olha meu irmao eu estou a disposição pra ajudar, mas eu só tenho um conhecimento rasuavel de codigo html rsrsr seria um problema?

**Comment by italozaina** [comment]
Opa já é o suficiente para revisão/correção envia seu whats (ddd + num) para o email italoczaina@gmail.com que eu passo mais informações de como cooperar com o projeto.

Deus abençoe
